coverage:
  round: up
  range: 80..100
  status:
    project:
      default:
        target: auto
        threshold: 20%
        base: auto 
        informational: true
    patch:
      default:
        target: auto
        threshold: 20%
        base: auto 
        informational: true
comment:
  layout: " diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: false

